default:
  dora_dir: /mnt/d/github/audiocraft/dora_output
  partitions:
    global: debug
    team: debug
  reference_dir: /tmp
darwin: # if we detect we are on a Mac, then most likely we are doing unit testing etc.
  dora_dir: /mnt/d/github/audiocraft/dora_output
  partitions:
    global: debug
    team: debug
  reference_dir: /tmp
